create table account (id bigint not null auto_increment, amount float(53) not null, bank_id bigint, person_id bigint, primary key (id)) engine=InnoDB;
create table bank (id bigint not null auto_increment, name varchar(255), primary key (id)) engine=InnoDB;
create table person (id bigint not null auto_increment, email varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table person_contactaccount (person_id bigint not null, account_id bigint not null, primary key (person_id, account_id)) engine=InnoDB;
create table transaction (id bigint not null auto_increment, amount float(53) not null, description varchar(255), transaction_date date, account_from_id bigint, account_to_id bigint, primary key (id)) engine=InnoDB;
alter table account add constraint FKawl1lrpngb7h5ktg79odeic5w foreign key (bank_id) references bank (id);
alter table account add constraint FKd9dhia7smrg88vcbiykhofxee foreign key (person_id) references person (id);
alter table person_contactaccount add constraint FKf9avxkukncptbrtugeubkycqj foreign key (account_id) references account (id);
alter table person_contactaccount add constraint FKc4f28hj34sgf2ujl3joio7cb5 foreign key (person_id) references person (id);
alter table transaction add constraint FKlax6nioh16qapni5oetnsocoh foreign key (account_from_id) references account (id);
alter table transaction add constraint FKi2std9osl77a5s35sf736s64 foreign key (account_to_id) references account (id);
